version: '3.6'
services:
  nginx:
    platform: linux/x86_64
    container_name: web-server
    image: nginx:latest
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/conf/:/etc/nginx/conf.d/
    ports:
      - '127.0.0.1:80:80'
    depends_on:
      - php
      - mysql

  php:
    platform: linux/x86_64
    container_name: php-server
    build:
      context: .
      dockerfile: php-dockerfile
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/

  mysql:
    image: mariadb:10.9
    container_name: mariadb-server
    volumes:
      - users_db:/var/lib/mysql
      - ./mysql_conf/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql_conf/.my.cnf:/root/.my.cnf 
      - ./mysql_conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: qazSedcS123
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./mysql_conf/phpmysql.conf:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=1


volumes:
  users_db: {}